AKBOCADO/urls.py
from django.urls import include, path
from music.views import home, index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home, name='home'),
    path('user/', include('user.urls')),
    path('music/', include('music.urls')),
    path('melon/', include('melon.urls')),
    path('index/', index),
]

# MEDIA 경로 추가
urlpatterns += static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

music/urls.py
from django.urls import path
from . import views

app_name = 'Music'

urlpatterns = [
    path('analyze/', views.analyze, name='analyze'),
    path('analyze_type/<type>/',views.analyze_type,name = 'analyze_type'),
    path('search/', views.search, name='search'),
    path('checkImage/',views.checkAkboImage, name='checkImage'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('checkid/', views.checkid, name='checkid'),
    path('myakbo/', views.myakbo, name='myakbo'),
    path('save/', views.save, name='save'),
    path('akboinfo/<int:pk>/', views.akboinfo, name='akboinfo')
]

user/models.py
from django.db import models
from matplotlib import artist
from matplotlib.pyplot import title

import user

class User(models.Model):
    userid = models.CharField(max_length=20, verbose_name='아이디')
    password = models.CharField(max_length=500, verbose_name='비밀번호')

    class Meta:
        db_table = 'Akbo_user'
        verbose_name = '유저'
        verbose_name_plural = '유저(들)'

    def __str__(self):
        return f'{self.userid} 유저'

class Akbo(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=30, verbose_name='제목')
    artist = models.CharField(max_length=50, verbose_name='아티스트', null=True)
    lyrics = models.TextField(verbose_name='가사', null=True)
    image = models.FileField(upload_to='akbo_image/', null=False)

    class Meta:
        db_table = 'Akbo_akbo'
        verbose_name = '악보'
        verbose_name_plural = '악보(들)'

        def __str__(self):
            return f'{self.id} - {self.title} 악보'

user/forms.py
from django import forms
from user.models import User

class LoginForm(forms.Form):
    userid = forms.CharField(
        error_messages={
            'required' : '아이디를 입력해주세요'
        },
        max_length=20,label='아이디'
    )
    password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=100,label='비밀번호'
    )


    def clean(self):
        cleaned_data = super().clean()

        self.userid = cleaned_data.get('userid')
        self.password = cleaned_data.get('password')

class JoinForm(forms.ModelForm):
    password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=500,label='비밀번호'
    )

    re_password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=500,label='비밀번호 확인'
    )

    class Meta:
        model = User
        fields = '__all__'

    def clean(self):   
        # 우선 부모 Form 의 clean() 수행 --> 값이 들어있지 않으면 error 처리 
        cleand_data = super().clean()
        
        self.userid = cleand_data.get('userid')
        self.password = cleand_data.get('password')

user/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth.hashers import make_password, check_password
from user.forms import JoinForm

from user.models import Akbo, User
from music.models import Input

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        userid = request.POST.get('userid', None)
        password = request.POST.get('password', None)

        res_data = {}

        if not(userid and password):  # 값이 다 입력되었는지 확인
            res_data['error'] = '모든 값을 입력해야 합니다'
        else:
            # 모델로부터 데이터를 가져와야 한다
            user = User.objects.get(userid=userid)
            # 비밀번호 비교
            if check_password(password, user.password):
                # 로그인 처리 (세션 사용)
                request.session['user'] = {'id': user.id, 'userid': user.userid}
                return redirect('/')   # 로그인 성공후 home 으로 redirect
            else:
                # 비밀번호 불일치.  로그인 실패 처리
                res_data['error'] = '비밀번호를 틀렸습니다'

        return render(request, 'login.html', res_data)

def logout(request):
    if request.session.get('user'):
        del(request.session['user'])
    return redirect('/')

def join(request):
    # 회원가입 처리
    if request.method=="POST":
        form = JoinForm(request.POST)
        if form.is_valid():
            user = User(
                userid = form.userid,
                password = make_password(form.password),
            )
            user.save()
        else: 
            print("join 실패")
        return redirect("/user/login/")
    else:
        form = JoinForm()
        return render(request,'join.html',{'form':form})

def checkid(request):
    userid = request.GET.get('userid')
    context={}
    try:
        User.objects.get(userid=userid)
    except:
        context['data'] = "not exist" # 아이디 중복 없음

    return JsonResponse(context)

def myakbo(request):
    user = User.objects.get(id=request.session.get('user').get('id'))
    akbos = Akbo.objects.filter(user=user)
    return render(request, 'myakbo.html', {'akbos': akbos})

def save(request):
    title = request.GET.get('title')
    artist = request.GET.get('artist')
    lyrics = request.GET.get('lyrics')
    image = request.GET.get('image')
    print('저장하기 ----')
    print('제목:', title)
    print('아티스트:', artist)
    print('가사:', lyrics)
    print('이미지:', image)
    akbo = Akbo(
        user=User.objects.get(id=request.session.get('user').get('id')),
        title=title,
        artist=artist,
        lyrics=lyrics,
        image=Input.objects.get(id=image).img,
    )
    akbo.save()
    return JsonResponse({'data': 'success'})

def akboinfo(request, pk):
    akbo = Akbo.objects.get(id=pk)
    print('내 악보정보-----')
    print('akbo')
    return render(request, 'akboinfo.html', {'akbo': akbo})

user/templates/akboinfo.html
{% extends 'base.html' %}

{% block modal %}
<div id='mo' style='position: absolute; background-color: rgba(0,0,0,0.5); width: 100%; height:100%; z-index: 20000;display: none;'>
    <div id="loadingmodal" class="modal" style='z-index:20002;height:400px;width:400px;'>
        <div class="loading-container">
            <div class="loading"></div>
            <div id="loading-text">분석 중</div>
        </div>        
    </div>
    <div id="resultmodal" class="modal result_modal" style='z-index: 20001'>
        <span class='close'>&times;</span>
        <img src="" alt="">
        <h2>분석 결과</h2>
        <h4 id='result'><p  style='margin:0;min-height:3%;'></p></h4>
    </div>
    <div id="artistmodal" class='modal'  style='z-index: 20002'>
        <span class='close'>&times;</span>
        <img src="" alt="" id='artistimage'>
        <h2 id='artistname'></h2>
        <hr>
        <div class="table-wrapper">
            <h4>최신곡</h4>
            <table class="alt" style='color: white;'>
                <thead>
                    <tr>
                        <th>title</th>
                        <th>artist</th>
                    </tr>
                </thead>
                <tbody id='artisttrack'>
                </tbody>
            </table>
        </div>
    </div>
    <div id='trackmodal' class='modal' style='z-index: 20002'>
        <span class="close">&times;</span>
        <h2 id="trackname"></h2>
        <hr>
        <div class="table-wrapper">
            <h4>인기곡</h4>
            <table class="alt" style='color: white;'>
                <thead>
                    <tr>
                        <th>title</th>
                        <th>artist</th>
                    </tr>
                </thead>
                <tbody id='titletrack'>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock  %}

{% block main %}
<div id="banner-wrapper">
    <section id="banner" class="container">
        <div class="row">
            <div id="content" class="col-12">
                <header class="major">
                    <h2>내 악보</h2>
                </header>
                <section class="col-8 col-12-narrower">
                    <div class="row">
                        <div class="col-6 col-12-narrower">
                            <img src="{{akbo.image.url}}" alt="악보" id='akbo_temp'>
                        </div>
                        <div class="col-6 col-12-narrower">
                            <ul class="profiles five" id='info'>
                                <li class="first">
                                    <div class="col-12">
                                        <h3>제목</h3>
                                        <p><a href="javascript:search('title', '{{akbo.title}}', '{{akbo.artist}}')" class='info'>{{akbo.title}}</a></p>
                                    </div>
                                </li>
                                <li>
                                    <div class='col-12'>
                                        <h3>아티스트</h3>
                                        <p><a href="javascript:search('artist', '{{akbo.artist}}', '{{akbo.artist}}')" class='info'>{{akbo.artist}}</a></p>
                                    </div>
                                </li>
                                <li>
                                    <div class='col-12'>
                                        <h3>가사</h3>
                                        <p>{{akbo.lyrics}}</p>
                                    </div>
                                </li>
                                <li class='col-12'>
                                    <div class="row">
                                        <div class="col-12">
                                            <button class="button large" id='play'>악보 재생</button>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
</div>
{% endblock  %}

{% block script %}
<style>
    .modal::-webkit-scrollbar {
        width: 10px;  /* 스크롤바의 너비 */
    }
    
    .modal::-webkit-scrollbar-thumb {
        height: 20%; /* 스크롤바의 길이 */
        background: #4D8E58; /* 스크롤바의 색상 */
        
        border-radius: 20px;
    }

    .modal::-webkit-scrollbar-track {
        background: rgba(33, 122, 244, .0);  /*스크롤바 뒷 배경 색상*/
        margin: 20px 0;
    }

    .modal{
        width: 600px;
        height:600px;
        top: 30%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #343e49;
        border: 3px solid white;
        position: absolute;
        border-radius: 1em;
        overflow-x: auto;
    }
    .close{
        position:fixed; 
        color: white;
        right: 1%;
        font-size: xx-large;
        font-weight: bold;
    }
    .close:hover{
        color: #4D8E58;
        font-size: xxx-large;
    }
    .modal h2, .modal h3, .modal h4{
        color: white;
        text-align: center;
        margin: 50px 0;
    }
    .modal img{
        margin-top: 20px;
        width: 100%;
        padding: 0 30%;
        border-radius: 1em;
    }
    thead td{
        font-weight: bold;
    }
    .modal td{
        padding: 3%;
        text-overflow: ellipsis;
        {% comment %} white-space: nowrap; {% endcomment %}
        overflow: hidden;
        width: 50%;
        text-align: center;
    }
    ul li p{
        color: white;
        text-align: center;
    }

    #akbo_temp{
        border: 2px solid white;
        border-radius: 1em;
        background-color: white;
        height: 50vh;
        padding: 3%;
    }
    ul#info{
        border: 2px solid white;
        border-radius: 1em;
        padding: 3%;
        background-color: #343e49;
    }
    a.info{
        text-decoration: none;
        color: white;
        display: block;
    }
</style>
<script>
    $('.close').click(function(){
        $('#mo').toggle()
    })

    $('#save').click(function(){
        if('{{request.session.user}}'){
            $.ajax({
                url: "{% url 'User:save' %}",
                type: 'GET',
                data: {
                    'title': '{{title}}',
                    'artist': '{{artist}}',
                    'lyrics': '{{lyrics}}',
                    'image': '{{image.id}}',
                },
                dataType: 'JSON',
                contentType: 'application/json; charset=utf-8',
                success: function(response){
                    if(response.data == 'success'){
                        alert('악보를 저장했습니다!')
                    }else{
                        alert('악보 저장에 실패했습니다.\n다시 시도해주세요.')
                    }
                }
            })
        }else{
            alert('로그인 후 이용해주세요.')
            return
        }
    })

    function search(type, item, artist){
        $.ajax({
            url: `{% url 'Music:search' %}?type=${type}&item=${item}&artist=${artist}`,
            success: function(response){
                console.log(response)

                if(type=='artist'){
                    $(`#${type}image`).attr('src', response['image'])
                    $(`#${type}name`).text(response['artist'])
                    for(track of response.tracks){
                        $('#artisttrack').append(
                            $('<tr></tr>')
                            .append($(`<td>${track.title}</td>`))
                            .append($(`<td>${track.artist}</td>`))
                        )
                    }
                    $('#artistmodal').show()
                }else if(type=='title'){
                    $(`#trackname`).text(response['track'])
                    for(track of response.tracks){
                        $('#titletrack').append(
                            $('<tr></tr>')
                            .append($(`<td>${track.title}</td>`))
                            .append($(`<td>${track.artist}</td>`))
                        )
                    }
                    $('#trackmodal').show()
                }
                $('#mo').show()
            }
        })
    }
</script>
{% endblock  %}

user/templates/join.html
{% extends 'base.html' %}
{% block title %}Akbocado - 회원가입{% endblock  %}
{% block main %}
<div id="banner-wrapper">
    <section id="banner" class="container">
        <div class="row">
            <div id="content" class="col-12">

                <header class="major">
                    <h2>회원가입</h2>
                </header>
                <section class="col-8 col-12-narrower">
                    <form method="post" action="{% url 'User:join' %}">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class='button primary fit'>작성 완료</button>
                    </form>
                </section>
            </div>
        </div>
    </section>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){

        id_flag = false
        pw_flag = false
        repw_flag = false

        // 아이디 중복검사
        // .attr({'data-bs-original-title': '중복된 아이디입니다.'}).tooltip("show");
        $('#id_userid').focus(function(){
            id_flag = false
        })
        $('#id_userid').change(function(){
            id = $('#id_userid').val().trim()
            if(id.length < 5){
                $('label[for=id_userid]').html('아이디: 최소 5글자 이상 입니다.').css({'color': 'red'})
                id_flag = false
            }
            else{
                $.ajax({
                    url: "{% url 'User:checkid' %}",
                    data: {'userid': id},
                    datatype:'json',
                    success: function(response){
                        if(response.data == 'not exist'){
                            $('label[for=id_userid]').html('아이디: 사용 가능한 아이디 입니다.').css({'color': 'white'})
                            id_flag = true
                            return;
                        }else{
                            $('label[for=id_userid]').html('아이디: 중복된 아이디 입니다.').css({'color': 'red'})
                            id_flag = false
                            return;
                        }
                    }
                })
            }
        })
        // 비밀번호 검사
        $('#id_password').focus(function(){
            pw_flag = false
            repw_flag = false
        })
        $('#id_password').change(function(){
            pw = $(this).val().trim()
            if(!/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/.test(pw)){
                $('label[for=id_password]').html('비밀번호: 유효하지 않은 비밀번호 입니다.').css({'color': 'red'})
                pw_flag = false
            }else{
                $('label[for=id_password]').html('비밀번호: 사용 가능한 비밀번호 입니다.').css({'color': 'white'})
                pw_flag = true
            }

            repw = $("#id_re_password").val().trim()
            if(pw != repw){
                $('label[for=id_re_password]').html('비밀번호 확인: 비밀번호가 일치하지 않습니다.').css({'color': 'red'})
                repw_flag = false
            }else{
                $('label[for=id_re_password]').html('비밀번호 확인: 확인되었습니다.').css({'color': 'white'})
                repw_flag = true
            }
        })
        // 비밀번호 확인 검사
        $('#id_re_password').focus(function(){
            pw_flag = false
            repw_flag = false
        })
        $('#id_re_password').change(function(){
            repw = $(this).val().trim()
            if(pw != repw){
                $('label[for=id_re_password]').html('비밀번호 확인: 비밀번호가 일치하지 않습니다.').css({'color': 'red'})
                repw_flag = false
            }else{
                $('label[for=id_re_password]').html('비밀번호 확인: 확인되었습니다.').css({'color': 'white'})
                repw_flag = true
            }
        })
    })
</script>
<style>
    p{
        text-align: left;
    }
    .checked{
        color:#ff8b77;
    }
</style>
{% endblock  %}

user/templates/login.html
{% extends 'base.html' %}

{% block title %}Akbocado - 로그인{% endblock title %}

{% block main %}
<div id="banner-wrapper">
    <section id="banner" class="container">
        <div class="row">
            <div id="content" class="col-12">

                <header class="major">
                    <h2>로그인</h2>
                </header>
                <section class="col-8 col-12-narrower">
                    <form method="post" action="{% url 'User:login' %}" id='loginform'>
                        {% csrf_token %}
                        <div class="row gtr-50 gtr-uniform">
                            <div class="col-12">
                                <input type="text" name="userid" id="userid" placeholder="아이디" />
                            </div>
                            <div class="col-12">
                                <input type="password" name="password" id="password" placeholder="비밀번호" />
                            </div>
                            <div class="col-12">
                                <ul class="actions" style='justify-content: center;'>
                                    <li><input type='submit' class="button alt2 col-6" style='border: 2px solid white;' value='로그인'/></li>
                                    <li><a href="{% url 'User:join' %}" class="button alt2 col-6" style='border: 2px solid white;'>회원가입</a></li>
                                </ul>
                            </div>      
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </section>
</div>
{% endblock  %}

user/templates/myakbo.html
{% extends 'base.html' %}

{% block title %}Akbocado - 내 악보{% endblock title %}

{% block main %}
<div id="banner-wrapper">
    <section id="banner" class="container">
        <div class="row">
            <div id="content" class="col-12">
                <header class="major">
                    <h2>{{request.session.user.userid}} 님의 악보</h2>
                </header>
            </div>
            <ul class="pennants">
                {% for akbo in akbos %}
                <li data="{{akbo.id}}">
                    <img src="{{akbo.image.url}}" alt="" style='width: 10em;'>
                    <h3>{{akbo.title}}</h3>
                    <p>{{akbo.artist}}</p>
                </li>
                {% endfor %}
            </ul>
        </div>
    </section>
</div>
{% endblock  %}
{% block script %}
<style>
    ul.pennants li{
        border: 2px solid white;
        border-radius: 1em;
        transition: all 0.3s;
        cursor: pointer;
    }
    ul.pennants li:hover{
        background-color: rgba(255,255,255,0.5);
        width: 16em;
        padding: 1.3em;
    }
</style>
<script>
    $('li').click(function(){
        pk=$(this).attr('data')
        location.href = "{% url 'User:akboinfo' pk=12345 %}".replace(/12345/, pk)
    })
</script>
{% endblock script %}