AKBOCADO/urls.py
from django.urls import include, path
from music.views import home, index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', home, name='home'),
    path('user/', include('user.urls')),
    path('music/', include('music.urls')),
    path('melon/', include('melon.urls')),
    path('index/', index),
]

# MEDIA 경로 추가
urlpatterns += static(
    settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT
)

melon/urls.py
from django.urls import path
from . import views

app_name = 'Melon'

urlpatterns = [
    path('analyze/', views.analyze, name='analyze'),
]

music/urls.py
from django.urls import path
from . import views

app_name = 'Music'

urlpatterns = [
    path('analyze/', views.analyze, name='analyze'),
    path('analyze_type/<type>/',views.analyze_type,name = 'analyze_type'),
    path('search/', views.search, name='search'),
    path('checkImage/',views.checkAkboImage, name='checkImage'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('checkid/', views.checkid, name='checkid'),
    path('myakbo/', views.myakbo, name='myakbo'),
    path('save/', views.save, name='save'),
    path('akboinfo/<int:pk>/', views.akboinfo, name='akboinfo')
]

music/models.py
from django.db import models

class Input(models.Model):
    img = models.FileField(upload_to='input/', default="")
    img_original = models.CharField(max_length=200, null=False)

    class Meta:
        db_table = 'Akbo_input'
        verbose_name = '게시판그림'
        verbose_name_plural = '게시판그림(들)'

music/views.py
from bs4 import BeautifulSoup
from django.http import JsonResponse
from django.shortcuts import render
import requests
from music.OCR.title import getTitle
from music.OCR.artist import getArtist
from music.models import Input
from . import modules

from tensorflow.keras.models import load_model
import PIL.ImageOps as ops
from PIL import Image
import numpy as np
import cv2 
from .OCR.lyrics import getLyrics

from io import BytesIO
import base64

model = load_model('model/akbo_model_p_nanpa.h5')

def home(request):
    return render(request, 'home.html')

def index(request):
    return render(request, 'index.html')


def analyze_type(request,type):
    original = Input.objects.get(pk = request.GET.get('img_id'))
    image = original.img
    akbo_image = cv2.imdecode(np.frombuffer(image.read(), np.uint8), cv2.IMREAD_UNCHANGED)
    if type == 'title':
        title= None
        title,title_imgs = getTitle(akbo_image)
        title_uri = to_data_uri(title_imgs)
        title = title or '알 수 없음'
        context = {
            'type':type,
            'title':title,
            'title_uri': title_uri,
            }
    elif type == 'artist':
        artist = None
        # artist, artist_imgs =
        # artist_uri = [to_data_uri(l) for l in artist_imgs]
        artist, artist_imgs = getArtist(akbo_image)
        artist = [(a.split(' ')[-1], ''.join(a.split(' ')[:-1])) for a in artist]
        artist_uri = [to_data_uri(a) for a in artist_imgs]
        artist = artist or ['알 수 없음']
        context = {
            'type' : type,
            'artist': artist,
            'artist_uri' : artist_uri,
        }
    elif type == 'lyrics':
        lyrics = None
        lyrics, lyrics_imgs = getLyrics(akbo_image)
        lyrics_uri = [to_data_uri(l) for l in lyrics_imgs]
        lyrics = lyrics or '알 수 없음'
        context = {
            'type' : type,
            'lyrics': lyrics,
            'lyrics_uri' : lyrics_uri,
        }
    elif type == 'note':
        # 음표 분석
        image_1 = modules.remove_noise(akbo_image) # 1. 보표 영역 추출 및 그 외 노이즈 제거
        image_2, staves = modules.remove_staves(image_1) # 2. 오선 제거
        image_3, staves = modules.normalization(image_2, staves, 10) # 3. 악보 이미지 정규화
        image_4, objects = modules.object_detection(image_3, staves) # 4. 객체 검출 과정
        image_5, objects = modules.object_analysis(image_4, objects) # 5. 객체 분석 과정
        image_6, key, beats_temp, pitches = modules.recognition(image_5, staves, objects) # 6. 인식 과정
        beats = [beat if beat >= 0 else -beat for beat in beats_temp]
        
        # errors = [i for i, pit in enumerate(pitches) if pit < 0]
        # for e in reversed(errors):
        #     del(beats[e])
        #     del(pitches[e])

        context = {
            'type': type,
            'key': key,
            'beats': beats,
            'pitches': pitches,
            # 'images': [image_1, image_2, image_3, image_4, image_5, image_6],
        }
        

    return JsonResponse(context)



def analyze(request):
    akbo = None; title = None; artist = None; lyrics = None

    akbo = request.FILES.get('akbo')
    buffer = akbo.read()

    original = Input(
        img=akbo,
        img_original=akbo.name,
    )

    original.save()

    # 분석 작업(이미지 -> np)
    image = original

    akbo_image = cv2.imdecode(np.frombuffer(buffer , np.uint8), cv2.IMREAD_UNCHANGED)
  
    context = {
        'image': image,
        'original': original,
    }
    print("=================",original.pk)

    return render(request, 'result.html', context)

def search(request):
    type = request.GET.get('type')
    item = request.GET.get('item')
    artist = request.GET.get('artist')

    print(f'입력 정보: {type}, {item}, {artist}')
    context = {}
    try:
        if type=='artist':
            melon_data = getMelonArtist(item)
            context['image'] = melon_data['image']
            context['artist'] = melon_data['artist']
            context['tracks'] = melon_data['tracks']
        elif type=='title':
            melon_data = getMelonInfo(item, artist)
            context['track'] = item
            context['tracks'] = melon_data
        print('곡 정보 크롤링 성공', context)
    except IndexError as ie:
        context['error'] = 'IndexError'
        print('곡 정보 크롤링 실패', ie)

    return JsonResponse(context)

def getMelonInfo(track, artist):
    query = f'{track}'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    q_url = 'https://www.melon.com/search/song/index.htm?q='+query
    try:
        tracks = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select('table tbody tr')
        data = [{
            'title': soup.select_one('.ellipsis a.fc_gray').text.strip(),
            'artist': soup.select_one('#artistName > a.fc_mgray').text.strip() if soup.select_one('#artistName > a.fc_mgray') else  'Various Artists',
            'album': soup.select_one('.ellipsis:not(#artistName) a.fc_mgray').text.strip(),
            } for soup in tracks[:10]]
    except Exception as e:
        return ('곡 정보 불러오기 실패', e)
    return data

def getMelonArtist(artist):
    q_url = 'https://www.melon.com/search/artist/index.htm?q='+artist
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    data = {}
    try:
        artistid = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select_one('#pageList .d_artist_list ul li .wrap_atist12 button.btn_join_fan')['data-artist-no']
        url = f"https://www.melon.com/artist/song.htm?artistId={artistid}#params%5BorderBy%5D=POPULAR_SONG_LIST&params%5B"
        soup = BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser')
        data['image'] = soup.select_one('#artistImgArea img').get('src')
        data['artist'] = soup.select_one('.title_atist').text.replace('아티스트명', '')
        data['tracks'] = [{
            'title': tr.select_one('.ellipsis a.fc_gray').text.strip(),
            'artist': tr.select_one('#artistName > a.fc_mgray').text.strip() if soup.select_one('#artistName > a.fc_mgray') else  'Various Artists',
            'album': tr.select_one('.ellipsis:not(#artistName) a.fc_mgray').text.strip(),
        }
        for tr in soup.select('#frm div.tb_list.d_song_list.songTypeOne table tbody tr')[:10]]
    except Exception as e:
        print(data)
        return ('아티스트 정보 불러오기 실패', e)
    return data


def checkAkboImage(request):
    akbo = "악보"
    akboImage = request.FILES.get('file')
    print(type(akboImage))
    img = akboImage.read()
    image = cv2.imdecode(np.frombuffer(img , np.uint8), cv2.IMREAD_UNCHANGED)
    # print("==========",img,"=============")
    result = predict(image)
    if result == 1:
        print("=========악보 아님==============")
        akbo = "일반"
    elif result == 2:
        akbo = '멜론'
    return JsonResponse({'data': akbo})


def predict(img):
    class_names = [0, 1, 2]
    mono8img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    resizeImg = cv2.resize(mono8img, dsize=(200, 200))
    data_arr = resizeImg.reshape(1, 200, 200, 1)
    preds = model.predict(data_arr)

    return class_names[np.argmax(preds[0])]

def to_data_uri(img):
    image = Image.fromarray(img)
    data = BytesIO()
    image.save(data, "png") # pick your format
    data64 = base64.b64encode(data.getvalue())
    return u'data:img/png;base64,'+data64.decode('utf-8') 

music/templates/base.html
<!DOCTYPE HTML>
<!--
	Iconic by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html>
	<head>
		<title>{% block title %}{% endblock  %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/static/assets/css/main.css" />
	</head>
	<body class="homepage is-preload" style='position: relative;'>
		{% block modal %}{% endblock  %}
		<div id="page-wrapper">

			<!-- Header Wrapper -->
			<div id="header-wrapper">

				<!-- Header -->
					<div id="header" class="container">

						<!-- Logo -->
							<h1><a href="{% url 'home' %}" id="logo">Akbocado</a></h1>

						<!-- Nav -->
							<nav id="nav">
								<ul>
									{% if request.session.user %}
										<li>
											<a class="dropdown">{{request.session.user.userid}}</a>
											<ul>
												<li><a href="{% url 'User:logout' %}">로그아웃</a></li>
												<li><a href="{% url 'User:myakbo' %}">내 악보</a></li>
											</ul>
										</li>
									{% else %}
										<li><a href="{% url 'User:login' %}">로그인</a></li>
									{% endif %}
								</ul>
							</nav>

					</div>

			</div>

			<div id="main-wrapper">
				{% block main %}{% endblock  %}
			</div>

			<div id="featured-wrapper">
				<section id='featured' class='container'>
					<div class="title">
						<span>Akbocado</span>
					</div>
				</section>
			</div>

			<!-- Copyright -->
				<div id="copyright">
					&copy; Untitled. All rights reserved.
				</div>

		</div>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.dropotron.min.js"></script>
			<script src="/static/assets/js/browser.min.js"></script>
			<script src="/static/assets/js/breakpoints.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<script src="/static/assets/js/main.js"></script>
	</body>
	{% block script %}{% endblock %}
</html>

music/templates/home.html
{% extends 'base.html' %}

{% block title %}Akbocado - 악보OCR{% endblock  %}

{% block modal %}
<div id='mo' style='position: absolute; background-color: rgba(0,0,0,0.5); width: 100%; height:100%; z-index: 200000;display: none;'>
    <div id="resultmodal" class='modal'>
        <h2>이미지 분석 중</h2>
        <img src="" alt="" id='inputimage'>
    </div>
</div>
{% endblock  %}

{% block main %}
<div id="banner-wrapper">
    <section id="banner" class="container">
        <div class="row">
            <div id="content" class="col-12">

                <header class="major">
                    <img src="/static/icon.png" alt="" style='width: 30%;'>
                </header>
                <section class="col-8 col-12-narrower">
                    <form action="{% url 'Music:analyze' %}" method="post" id='akboform' class='dropzone' enctype="multipart/form-data" style='position:relative;'>
                        {% csrf_token %}
                        <label for="akbo" id='akbo'>파일을 업로드해주세요.</label>
                        <input type="file" name="akbo" id="akb" style='color:transparent;'>
                    </form>
                </section>
            </div>
        </div>
    </section>
</div>
{% endblock  %}
{% block script %}
<link rel="stylesheet" href="/static/live-border.css">
<script src="/static/live-border.js"></script>
<style>
    .modal{
        width: 500px;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #343e49;
        border: 3px solid white;
        position: fixed;
        border-radius: 1em;
        overflow: hidden;
    }
    .close{
        position:absolute; 
        color: white;
        right: 1%;
        font-size: xx-large;
        font-weight: bold;
    }
    .close:hover{
        color: #4D8E58;
        font-size: xxx-large;
    }
    .modal h2, .modal h3, .modal h4{
        color: white;
        text-align: center;
        margin: 50px 0;
    }
    .modal img{
        width: 80%;
        padding: 20%;
        margin: 10%;
        border-radius: 1em;
    }
    thead td{
        font-weight: bold;
    }
    .modal td{
        padding: 3%;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        width: 50%;
        text-align: center;
    }
    ul li p{
        color: white;
        text-align: center;
    }


    #akbo{
        position: absolute;
        left: 40%;
        top: 45%;
        width: 20%;
        color: #4D8E58;
        font-weight: bold;
    }
    #akb{
        outline: 2px dashed #4D8E58;
        outline-offset:-40px;  
        text-align: center;
        transition: all .15s ease-in-out;
        width: 50%;
        height: 500px;
        background-color: lightgray;
        margin: 10% auto;
        border-radius: 1em;
        display: block;
    }
    #akb:hover{
        background-color: gray;
        outline-offset: -5px;
    }
    #akb::file-selector-button {
        display: none;
    }
</style>
<script>
    $('#akb')
    .on("dragover", dragOver)
    .on("dragleave", dragOver)
    .on("drop", uploadFiles);

    $('#akb').change(uploadFiles)
 
    function dragOver(e){
        e.stopPropagation();
        e.preventDefault();
        if (e.type == "dragover") {
            $(e.target).css({
                "background-color": "gray",
                "outline-offset": "-5px"
            });
        } else {
            $(e.target).css({
                "background-color": "lightgray",
                "outline-offset": "-40px"
            });
        }
    }

    function uploadFiles(e){
        var akboImage = $('#akb')[0].files[0]

        // 로딩 화면 만들기
        readURL($('#akb')[0])
        $('#mo').show()

        // 혜원 - 악보확인 ajax
        var formdata = new FormData();
        formdata.append('file',akboImage);
        formdata.append('csrfmiddlewaretoken', '{{ csrf_token }}')
        console.log(formdata)
        $.ajax({
            url: "{% url 'Music:checkImage' %}",
            processData : false,
            contentType: false,
            type: "POST",
            data: formdata,
            success:function(response){
                console.log(response.data)
                if(response.data == '악보'){
                    $('#akboform').submit();
                }else if(response.data == '일반'){
                    alert('악보가 아닙니다.\n악보를 선택해주세요.');
                    location.reload();
                }else if(response.data == '멜론'){
                    $('#akboform').attr('action', "{% url 'Melon:analyze' %}").submit();
                }
            }
        })
    }

    function readURL(input) {
        if (input.files && input.files[0]) {
          var reader = new FileReader();
          reader.onload = function(e) {
            document.getElementById('inputimage').src = e.target.result;
          };
          reader.readAsDataURL(input.files[0]);
        } else {
          document.getElementById('inputimage').src = "";
        }
    }

    $("#inputimage").liveBorder({top:true, bottom:false});
</script>
{% endblock  %}

music/templates/index.html
<!DOCTYPE HTML>
<!--
	Iconic by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html>
	<head>
		<title>Untitled</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/static/assets/css/main.css" />
	</head>
	<body class="homepage is-preload">
		<div id="page-wrapper">

			<!-- Header Wrapper -->
				<div id="header-wrapper">

					<!-- Header -->
						<div id="header" class="container">

							<!-- Logo -->
								<h1><a href="index.html" id="logo">Iconic</a></h1>

							<!-- Nav -->
								<nav id="nav">
									<ul>
										<li><a href="index.html">Home</a></li>
										<li>
											<a href="#">Dropdown</a>
											<ul>
												<li><a href="#">Lorem ipsum dolor</a></li>
												<li><a href="#">Magna phasellus</a></li>
												<li><a href="#">Etiam dolore nisl</a></li>
												<li>
													<a href="#">Phasellus consequat</a>
													<ul>
														<li><a href="#">Lorem ipsum dolor</a></li>
														<li><a href="#">Phasellus consequat</a></li>
														<li><a href="#">Magna phasellus</a></li>
														<li><a href="#">Etiam dolore nisl</a></li>
														<li><a href="#">Veroeros feugiat</a></li>
													</ul>
												</li>
												<li><a href="#">Veroeros feugiat</a></li>
											</ul>
										</li>
										<li><a href="left-sidebar.html">Left Sidebar</a></li>
										<li><a href="right-sidebar.html">Right Sidebar</a></li>
										<li><a href="no-sidebar.html">No Sidebar</a></li>
									</ul>
								</nav>

						</div>

				</div>

			<!-- Main Wrapper -->
				<div id="main-wrapper">

					<!-- Main -->
						<div id="banner-wrapper">
							<section id="banner" class="container">
								<div class="row">
									<div id="content" class="col-12">

										<header class="major">
											<h2>Ipsum sed feugiat</h2>
											<p>Pharetra vivamus feugiat cursus metus commodo.</p>
										</header>

										<ul class="pennants">
											<li>
												<a href="#" class="pennant"><span class="icon solid fa-laptop"></span></a>
												<header>
													<h3>Diam et faucibus</h3>
												</header>
												<p>Aliquet dis eu suscipit nisl nascetur commodo etiam diam. Egestas vestibulum sem.</p>
											</li>
											<li>
												<a href="#" class="pennant"><span class="icon solid fa-cog"></span></a>
												<header>
													<h3>Risus ante cras</h3>
												</header>
												<p>Condi Accumsan cubilia sed purus sed erat lorem lorem lobortis sed vestibulum.</p>
											</li>
											<li>
												<a href="#" class="pennant"><span class="icon solid fa-chart-bar"></span></a>
												<header>
													<h3>Libero pulvinar</h3>
												</header>
												<p>Natoque sociis tristique accumsan eu malesuada. Vulputate sagittis sed semper.</p>
											</li>
											<li>
												<a href="#" class="pennant"><span class="icon solid fa-laptop"></span></a>
												<header>
													<h3>Diam et faucibus</h3>
												</header>
												<p>Aliquet dis eu suscipit nisl nascetur commodo etiam diam. Egestas vestibulum.</p>
											</li>
										</ul>

										<footer>
											<a href="#" class="button large">Sapien magna et feugiat</a>
										</footer>

									</div>
								</div>
							</section>
						</div>

				</div>

			<!-- Featured Wrapper -->
				<div id="featured-wrapper">

					<!-- Featured -->
						<section id="featured" class="container">
							<div class="title"><span>Urna porta gravida</span></div>
							<div class="row">

								<div class="col-6 col-12-narrower">
									<header>
										<h2>Sed tincidunt lacus</h2>
										<p>Odio amet quam at praesent quam iaculis</p>
									</header>
									<p>Hendrerit eu mollis imperdiet nibh ac hendrerit neque scelerisque curabitur. Ligula consequat turpis feugiat penatibus ultrices ipsum blandit. Nulla tortor metus proin nascetur. Neque gravida arcu dolor posuere gravida pulvinar at ultricies. Lacus massa montes sed ipsum lorem dolor blandit feugiat sed tempus lorem ipsum dolor. Neque gravida arcu dolor posuere gravida pulvinar at ultricies. Lacus massa montes sed ipsum lorem dolor blandit feugiat sed tempus lorem ipsum dolor. Ligula consequat turpis feugiat penatibus ultrices ipsum blandit. Nulla tortor metus proin nascetur. Neque gravida arcu dolor posuere gravida.</p>
									<footer>
										<a href="#" class="button">Eget suscipit pretium</a>
									</footer>
								</div>

								<div class="col-6 col-12-narrower">
									<ul class="profiles three">
										<li class="first">
											<div class="row">
												<div class="col-4 col-12-narrower">
													<a href="#" class="image fit"><img src="images/placeholder.jpg" alt="" /></a>
												</div>
												<div class="col-8 col-12-narrower">
													<h3>Elena Anderson</h3>
													<p>Adipiscing quam fringilla dis curae lorem ipsum dolor sit conseqeuat feugiat lorem.</p>
												</div>
											</div>
										</li>
										<li>
											<div class="row">
												<div class="col-4 col-12-narrower">
													<a href="#" class="image fit"><img src="images/placeholder.jpg" alt="" /></a>
												</div>
												<div class="col-8 col-12-narrower">
													<h3>Michael Aguilar</h3>
													<p>Adipiscing quam fringilla dis curae lorem ipsum dolor sit conseqeuat feugiat lorem.</p>
												</div>
											</div>
										</li>
										<li>
											<div class="row">
												<div class="col-4 col-12-narrower">
													<a href="#" class="image fit"><img src="images/placeholder.jpg" alt="" /></a>
												</div>
												<div class="col-8 col-12-narrower">
													<h3>Kate Carrera</h3>
													<p>Adipiscing quam fringilla dis curae lorem ipsum dolor sit conseqeuat feugiat lorem.</p>
												</div>
											</div>
										</li>
									</ul>
								</div>

							</div>
						</section>

				</div>

			<!-- Footer Wrapper -->
				<div id="footer-wrapper">

					<!-- Footer -->
						<div id="footer" class="container">

							<div class="title"><span>Amet dictum mattis</span></div>

							<div class="row">

								<!-- Form -->
									<section class="col-8 col-12-narrower">
										<header>
											<h2>Elit et euismod accumsan</h2>
										</header>
										<form method="post" action="#">
											<div class="row gtr-50 gtr-uniform">
												<div class="col-6 col-12-narrower">
													<input type="text" name="name" id="name" placeholder="Name" />
												</div>
												<div class="col-6 col-12-narrower">
													<input type="text" name="email" id="email" placeholder="Email" />
												</div>
												<div class="col-12">
													<input type="text" name="subject" id="subject" placeholder="Subject" />
												</div>
												<div class="col-12">
													<textarea name="message" id="message" placeholder="Message"></textarea>
												</div>
												<div class="col-12">
													<ul class="actions">
														<li><a href="#" class="button alt2">Send Message</a></li>
														<li><a href="#" class="button alt">Clear Form</a></li>
													</ul>
												</div>
											</div>
										</form>
									</section>

								<!-- Other -->
									<section class="col-4 col-12-narrower">
										<header>
											<h2>Adipiscing rhoncus</h2>
										</header>
										<ul class="icons">
											<li class="icon brands fa-twitter">
												<a href="http://twitter.com/n33co">@untitled-corp</a>
											</li>
											<li class="icon brands fa-facebook-f">
												<a href="#">facebook.com/untitled-corp</a>
											</li>
											<li class="icon brands fa-linkedin-in">
												<a href="#">linkedin.com/untitled-corp</a>
											</li>
											<li class="icon solid fa-envelope">
												<a href="#">info@untitled.tld</a>
											</li>
											<li class="icon solid fa-phone">
												<span>(000) 000-0000</span>
											</li>
											<li class="icon solid fa-home">
												<span>
													1234 Fictional Road #789<br />
													Nashville, TN 00000<br />
													United States
												</span>
											</li>
										</ul>
									</section>

							</div>

						</div>

				</div>

			<!-- Copyright -->
				<div id="copyright">
					&copy; Untitled. All rights reserved.
				</div>

		</div>

		<!-- Scripts -->
			<script src="static/assets/js/jquery.min.js"></script>
			<script src="static/assets/js/jquery.dropotron.min.js"></script>
			<script src="static/assets/js/browser.min.js"></script>
			<script src="static/assets/js/breakpoints.min.js"></script>
			<script src="static/assets/js/util.js"></script>
			<script src="static/assets/js/main.js"></script>

	</body>
</html>